examples:
  Structure:
    Structure/Coordinates: Coordinates
    Structure/WidthAndHeight: Width and Height
    Structure/SetupAndDraw: Setup and Draw
    Structure/NoLoop: No Loop
    Structure/Loop: Loop
    Structure/Redraw: Redraw
    Structure/Functions: Functions
    Structure/Recursion: Recursion
    Structure/CreateGraphics: Create Graphics

  Form:
    Form/PointsAndLines: Points and Lines
    Form/ShapePrimitives: Shape Primitives
    Form/PieChart: Pie Chart

reference:
  Environment:
    describe(), describeWithDisplay():
      - Environment/Describe0
      - Environment/Describe1
    describeElement(), describeElementWithDisplay():
      - Environment/DescribeElement
    textOutput(), textOutputWithDisplay():
      - Environment/TextOutput0
      - Environment/TextOutput1
    gridOutput(), gridOutputWithDisplay():
      - Environment/GridOutput0
      - Environment/GridOutput1
    print():
      - Environment/Print
    frameCount:
      - Environment/FrameCount
    deltaTime:
      - Environment/DeltaTime
    focused:
      - Environment/Focused
    cursor(), cursorX(), cursorXY():
      - Environment/Cursor
    frameRate(), getFrameRate(), setFrameRate():
      - Environment/FrameRate
    getTargetFrameRate():
      - Environment/GetTargetFrameRate
    noCursor():
      - Environment/NoCursor
    displayWidth:
      - Environment/DisplayWidth
    displayHeight:
      - Environment/DisplayWidth
    windowWidth:
      - Environment/WindowWidth
    windowHeight:
      - Environment/WindowWidth
    windowResized():
      - Environment/WindowResized
    width:
      - Environment/DisplayDensity
    height:
      - Environment/DisplayDensity
    fullscreen(), getFullscreen(), setFullscreen():
      - Environment/Fullscreen
    pixelDensity(), getPixelDensity(), setPixelDensity():
      - Environment/PixelDensity0
      - Environment/PixelDensity1
    displayDensity(), getDisplayDensity():
      - Environment/DisplayDensity
    getURL():
      - Environment/GetUrl
    getURLPath():
      - Environment/GetUrlPath
    getURLParams():
      - Environment/GetUrlParams
  Color:
    alpha():
      - Color/Alpha
    blue():
      - Color/Blue
    brightness():
      - Color/Brightness0
      - Color/Brightness1
    color():
      - Color/Color0
      - Color/Color1
      - Color/Color2
      - Color/Color3
      - Color/Color4
      - Color/Color5
      - Color/Color6
      - Color/Color7
    green():
      - Color/Green
    hue():
      - Color/Hue
    lerpColor():
      - Color/LerpColor
    lightness():
      - Color/Lightness
    red():
      - Color/Red
    saturation():
      - Color/Saturation
    background():
      - Color/Background0
      - Color/Background1
      - Color/Background2
      - Color/Background3
      - Color/Background4
      - Color/Background5
      - Color/Background6
      - Color/Background7
      - Color/Background8
      - Color/Background9
      - Color/Background10
    clear(), clearWebgl():
      - Color/Clear
    colorMode(), colorModeMaxAll(), colorModeMax(), colorModeMaxAlpha():
      - Color/ColorMode0
      - Color/ColorMode1
      - Color/ColorMode2
      - Color/ColorMode3
    fill():
      - Color/Fill0
      - Color/Fill1
      - Color/Fill2
      - Color/Fill3
      - Color/Fill4
      - Color/Fill5
      - Color/Fill6
      - Color/Fill7
      - Color/Fill8
      - Color/Fill9
      - Color/Fill10
    noFill():
      - Color/NoFill0
      - Color/NoFill1
    p5.Color/toString(), p5.Color/toStringf():
      - Color/P5ColorToString0
      - Color/P5ColorToString1
    p5.Color/setRed():
      - Color/P5ColorSetRed
    p5.Color/setGreen():
      - Color/P5ColorSetGreen
    p5.Color/setBlue():
      - Color/P5ColorSetBlue
    p5.Color/setAlpha():
      - Color/P5ColorSetAlpha
  Shape:
    circle():
      - Shape/Circle
