examples:
  Structure:
    Structure/Coordinates: Coordinates
    Structure/WidthAndHeight: Width and Height
    Structure/SetupAndDraw: Setup and Draw
    Structure/NoLoop: No Loop
    Structure/Loop: Loop
    Structure/Redraw: Redraw
    Structure/Functions: Functions
    Structure/Recursion: Recursion
    Structure/CreateGraphics: Create Graphics

  Form:
    Form/PointsAndLines: Points and Lines
    Form/ShapePrimitives: Shape Primitives
    Form/PieChart: Pie Chart

reference:
  Environment:
    describe():
      - Environment/Describe0
      - Environment/Describe1
  Shape:
    circle():
      - Shape/Circle
