examples:
  Structure:
    Structure/Coordinates: Coordinates
    Structure/WidthAndHeight: Width and Height
    Structure/SetupAndDraw: Setup and Draw
    Structure/NoLoop: No Loop
    Structure/Loop: Loop
    Structure/Redraw: Redraw
    Structure/Functions: Functions
    Structure/Recursion: Recursion
    Structure/CreateGraphics: Create Graphics

  Form:
    Form/PointsAndLines: Points and Lines
    Form/ShapePrimitives: Shape Primitives
    Form/PieChart: Pie Chart

reference:
  Environment:
    describe(), describeWithDisplay():
      - Environment/Describe0
      - Environment/Describe1
    describeElement(), describeElementWithDisplay():
      - Environment/DescribeElement
    textOutput(), textOutputWithDisplay():
      - Environment/TextOutput0
      - Environment/TextOutput1
    gridOutput(), gridOutputWithDisplay():
      - Environment/GridOutput0
      - Environment/GridOutput1
    print():
      - Environment/Print
    frameCount:
      - Environment/FrameCount
    deltaTime:
      - Environment/DeltaTime
    focused:
      - Environment/Focused
    cursor(), cursorX(), cursorXY():
      - Environment/Cursor
    frameRate(), getFrameRate(), setFrameRate():
      - Environment/FrameRate
    getTargetFrameRate():
      - Environment/GetTargetFrameRate
    noCursor():
      - Environment/NoCursor
    displayWidth:
      - Environment/DisplayWidth
    displayHeight:
      - Environment/DisplayWidth
    windowWidth:
      - Environment/WindowWidth
    windowHeight:
      - Environment/WindowWidth
    windowResized():
      - Environment/WindowResized
    width:
      - Environment/DisplayDensity
    height:
      - Environment/DisplayDensity
    fullscreen(), getFullscreen(), setFullscreen():
      - Environment/Fullscreen
    pixelDensity(), getPixelDensity(), setPixelDensity():
      - Environment/PixelDensity0
      - Environment/PixelDensity1
    displayDensity(), getDisplayDensity():
      - Environment/DisplayDensity
    getURL():
      - Environment/GetUrl
    getURLPath():
      - Environment/GetUrlPath
    getURLParams():
      - Environment/GetUrlParams
  Color:
    alpha():
      - Color/Alpha
    blue():
      - Color/Blue
    brightness():
      - Color/Brightness0
      - Color/Brightness1
    color():
      - Color/Color0
      - Color/Color1
      - Color/Color2
      - Color/Color3
      - Color/Color4
      - Color/Color5
      - Color/Color6
      - Color/Color7
    green():
      - Color/Green
    hue():
      - Color/Hue
    lerpColor():
      - Color/LerpColor
    lightness():
      - Color/Lightness
    red():
      - Color/Red
    saturation():
      - Color/Saturation
    background(), backgroundImage():
      - Color/Background0
      - Color/Background1
      - Color/Background2
      - Color/Background3
      - Color/Background4
      - Color/Background5
      - Color/Background6
      - Color/Background7
      - Color/Background8
      - Color/Background9
      - Color/Background10
    clear(), clearWebgl():
      - Color/Clear
    colorMode(), colorModeMaxAll(), colorModeMax(), colorModeMaxAlpha():
      - Color/ColorMode0
      - Color/ColorMode1
      - Color/ColorMode2
      - Color/ColorMode3
    fill():
      - Color/Fill0
      - Color/Fill1
      - Color/Fill2
      - Color/Fill3
      - Color/Fill4
      - Color/Fill5
      - Color/Fill6
      - Color/Fill7
      - Color/Fill8
      - Color/Fill9
      - Color/Fill10
    noFill():
      - Color/NoFill0
      - Color/NoFill1
    noStroke():
      - Color/NoStroke0
      - Color/NoStroke1
    stroke():
      - Color/Stroke0
      - Color/Stroke1
      - Color/Stroke2
      - Color/Stroke3
      - Color/Stroke4
      - Color/Stroke5
      - Color/Stroke6
      - Color/Stroke7
      - Color/Stroke8
      - Color/Stroke9
      - Color/Stroke10
    erase():
      - Color/Erase0
      - Color/Erase1
      - Color/Erase2
    noErase():
      - Color/NoErase
    p5.Color/toString(), p5.Color/toStringf():
      - Color/P5ColorToString0
      - Color/P5ColorToString1
    p5.Color/setRed():
      - Color/P5ColorSetRed
    p5.Color/setGreen():
      - Color/P5ColorSetGreen
    p5.Color/setBlue():
      - Color/P5ColorSetBlue
    p5.Color/setAlpha():
      - Color/P5ColorSetAlpha
  Shape:
    arc(), arcWithMode(), archWithDetail():
      - Shape/Arc0
      - Shape/Arc1
      - Shape/Arc2
      - Shape/Arc3
      - Shape/Arc4
    ellipse():
      - Shape/Ellipse
    circle():
      - Shape/Circle
    line(), line2D(), line3D():
      - Shape/Line0
      - Shape/Line1
    point(), point2D(), point3D(), pointFromVector():
      - Shape/Point0
      - Shape/Point1
      - Shape/Point2
    quad(), quad3D(), quadWithDetail(), quad3DWithDetail():
      - Shape/Quad
    rect(), roundedRect(), rectWithDetail():
      - Shape/Rect0
      - Shape/Rect1
      - Shape/Rect2
    square(), roundedSquare():
      - Shape/Square0
      - Shape/Square1
      - Shape/Square2
    triangle():
      - Shape/Triangle
    ellipseMode():
      - Shape/EllipseMode0
      - Shape/EllipseMode1
    noSmooth():
      - Shape/NoSmooth
    rectMode():
      - Shape/RectMode0
      - Shape/RectMode1
    smooth():
      - Shape/NoSmooth
    strokeCap():
      - Shape/StrokeCap
    strokeJoin():
      - Shape/StrokeJoin0
      - Shape/StrokeJoin1
      - Shape/StrokeJoin2
    strokeWeight():
      - Shape/StrokeWeight0
      - Shape/StrokeWeight1
    bezier(), bezier3D():
      - Shape/Bezier0
      - Shape/Bezier1
    bezierDetail():
      - Shape/BezierDetail
    bezierPoint():
      - Shape/BezierPoint
    bezierTangent():
      - Shape/BezierTangent0
      - Shape/BezierTangent1
    curve(), curve3D():
      - Shape/Curve0
      - Shape/Curve1
      - Shape/Curve2
    curveDetail():
      - Shape/CurveDetail
    curveTightness():
      - Shape/CurveTightness
    curvePoint():
      - Shape/CurvePoint
    curveTangent():
      - Shape/CurveTangent
    beginContour():
      - Shape/BeginContour
    endContour():
      - Shape/BeginContour
    bezierVertex(), bezierVertex3D():
      - Shape/BezierVertex0
      - Shape/BezierVertex1
      - Shape/BezierVertex2
    curveVertex(), curveVertex3D():
      - Shape/CurveVertex
    beginShape(), beginShapeWithMode():
      - Shape/BeginShape0
      - Shape/BeginShape1
      - Shape/BeginShape2
      - Shape/BeginShape3
      - Shape/BeginShape4
      - Shape/BeginShape5
      - Shape/BeginShape6
      - Shape/BeginShape7
      - Shape/BeginShape8
      - Shape/BeginShape9
      - Shape/BeginShape10
    quadraticVertex(), quadraticVertex3D():
      - Shape/QuadraticVertex0
      - Shape/QuadraticVertex1
    vertex(), vertex3D():
      - Shape/Vertex0
      - Shape/Vertex1
      - Shape/Vertex2
      - Shape/Vertex3
      - Shape/Vertex4
    normal():
      - Shape/Normal
    plane():
      - Shape/Plane
    box(), cube(), boxWithDetail(), boxWithDefaults():
      - Shape/Box
    sphere(), sphereWithDetail():
      - Shape/Sphere0
      - Shape/Sphere1
      - Shape/Sphere2
    cylinder(), cylinderWithDefaults(), cylinderWithDetail(), cylinderWithDetailAndCap():
      - Shape/Cylinder0
      - Shape/Cylinder1
      - Shape/Cylinder2
    cone(), coneWithDefaults(), coneWithDetail(), coneWithDetailAndCap():
      - Shape/Cone0
      - Shape/Cone1
      - Shape/Cone2
    ellipsoid(), ellipsoidWithDefaults(), ellipsoidWithDetail():
      - Shape/Ellipsoid0
      - Shape/Ellipsoid1
      - Shape/Ellipsoid2
    loadModel(), loadModelWithCallbacks(), loadModelWithCallbacksAndFileType():
      - Shape/Model
      - Shape/LoadModel
    model():
      - Shape/Model
    p5.Geometry/computeFaces(): ~
    p5.Geometry/computeNormals(): ~
    p5.Geometry/averageNormals(): ~
    p5.Geometry/averagePoleNormals(): ~
    p5.Geometry/normalize(): ~
  Structure:
    preload():
      - Structure/Preload
    setup():
      - Structure/Setup
    draw():
      - Structure/Draw
    subscriptions:
      - Structure/Subscriptions
    remove():
      - Structure/Remove
    disableFriendlyErrors:
      - Structure/DisableFriendlyErrors
    noLoop():
      - Structure/NoLoop0
      - Structure/NoLoop1
    loop():
      - Structure/NoLoop1
    isLooping():
      - Structure/IsLooping
    push():
      - Structure/Push0
      - Structure/Push1
    pop():
      - Structure/Push0
      - Structure/Push1
    redraw():
      - Structure/Redraw0
      - Structure/Redraw1
  # TODO: implement DOM functions last, since we want to focus on drawing.
  DOM:
    createSlider(), createSliderWithOptions():
      - DOM/CreateSlider0
      - DOM/CreateSlider1
  Rendering:
    p5.Graphics/reset():
      - Rendering/P5GraphicsReset
    p5.Graphics/remove():
      - Rendering/P5GraphicsRemove0
      - Rendering/P5GraphicsRemove1
    createCanvas(), createWebGLCanvas(), createCanvasWithMode(), createCanvasAndReturn():
      - Rendering/CreateCanvas
    resizeCanvas(), resizeCanvasWithoutRedraw():
      - Rendering/ResizeCanvas
    noCanvas():
      - Rendering/NoCanvas
    createGraphics(), createWebGLGraphics():
      - Rendering/CreateGraphics
    blendMode():
      - Rendering/BlendMode0
      - Rendering/BlendMode1
    drawingContext:
      - Rendering/DrawingContext
    setAttributes(), setAttribute():
      - Rendering/SetAttributes0
      - Rendering/SetAttributes1
      - Rendering/SetAttributes2
    applyMatrix(), applyMatrix2x3(), applyMatrix4x4():
      - Transform/ApplyMatrix0
      - Transform/ApplyMatrix1
      - Transform/ApplyMatrix2
      - Transform/ApplyMatrix3
      - Transform/ApplyMatrix4
      - Transform/ApplyMatrix5
    resetMatrix():
      - Transform/ResetMatrix
    rotate():
      - Transform/Rotate
    rotateX():
      - Transform/RotateX
    rotateY():
      - Transform/RotateY
    rotateZ():
      - Transform/RotateZ
    scale(), scaleXY(), scaleXYZ(), scale3D(), scaleFromVector(), scaleFromValues():
      - Transform/Scale0
      - Transform/Scale1
    shearX():
      - Transform/ShearX
    shearY():
      - Transform/ShearY
    translate(), translateZ(), translate3D(), translateFromVector():
      - Transform/Translate0
      - Transform/Translate1
      - Transform/Translate2
  # See DOM; implement these later.
  Data:
    storeItem(): ~
  Events:
    deviceOrientation: ~
    accelerationX:
      - Events/AccelerationX
    accelerationY:
      - Events/AccelerationY
    accelerationZ:
      - Events/AccelerationZ
    pAccelerationX: ~
    pAccelerationY: ~
    pAccelerationZ: ~
    rotationX:
      - Events/RotationX
    rotationY:
      - Events/RotationY
    rotationZ:
      - Events/RotationZ
    pRotationX:
      - Events/RotationX
    pRotationY:
      - Events/RotationY
    pRotationZ:
      - Events/RotationZ
    turnAxis:
      - Events/TurnAxis
    setMoveThreshold():
      - Events/SetMoveTreshold
    setShakeThreshold():
      - Events/SetShakeTreshold
    deviceMoved():
      - Events/DeviceMoved
    deviceShaken():
      - Events/DeviceShaken
    deviceTurned():
      - Events/DeviceTurned
      - Events/TurnAxis
    keyIsPressed:
      - Events/KeyIsPressed
    key:
      - Events/Key
    keyCode:
      - Events/KeyCode0
      - Events/KeyCode1
    keyPressed():
      - Events/KeyPressed0
      - Events/KeyPressed1
      - Events/KeyPressed2
    keyReleased():
      - Events/KeyReleased
    keyTyped():
      - Events/KeyTyped
    keyIsDown(), keyCodeIsDown():
      - Events/KeyIsDown0
      - Events/KeyIsDown1
    movedX:
      - Events/MovedX
    movedY:
      - Events/MovedY
    mouseX:
      - Events/MouseX
    mouseY:
      - Events/MouseY
    winMouseX:
      - Events/WinMouseX
    winMouseY:
      - Events/WinMouseY
    pwinMouseX:
      - Events/PWinMouseX
    pwinMouseY:
      - Events/PWinMouseY
    mouseButton:
      - Events/MouseButton
    mouseIsPressed:
      - Events/MouseIsPressed
    mouseMoved():
      - Events/MouseMoved0
      - Events/MouseMoved1
      - Events/MouseMoved2
    mouseDragged():
      - Events/MouseDragged0
      - Events/MouseDragged1
      - Events/MouseDragged2
    mousePressed():
      - Events/MousePressed0
      - Events/MousePressed1
      - Events/MousePressed2
    mouseReleased():
      - Events/MouseReleased0
      - Events/MouseReleased1
      - Events/MouseReleased2
    mouseClicked():
      - Events/MouseClicked0
      - Events/MouseClicked1
      - Events/MouseClicked2
    doubleClicked():
      - Events/DoubleClicked0
      - Events/DoubleClicked1
      - Events/DoubleClicked2
    mouseWheel():
      - Events/MouseWheel
    requestPointerLock():
      - Events/RequestPointerLock
    exitPointerLock():
      - Events/ExitPointerLock
    touches:
      - Events/Touches
    touchStarted():
      - Events/TouchStarted0
      - Events/TouchStarted1
      - Events/TouchStarted2
    touchMoved():
      - Events/TouchMoved0
      - Events/TouchMoved1
      - Events/TouchMoved2
    touchEnded():
      - Events/TouchEnded0
      - Events/TouchEnded1
      - Events/TouchEnded2
  Image:
    createImage():
      - Image/CreateImage0
      - Image/CreateImage1
      - Image/CreateImage2
    saveCanvas(), saveCanvasAs(), saveSpecificCanvas(), saveSpecificCanvasAs():
      - Image/SaveCanvas0
      - Image/SaveCanvas1
    saveFrames(), saveFramesWithCallback():
      - Image/SaveFrames
    p5.Image/width:
      - Image/P5ImageWidth
    p5.Image/height:
      - Image/P5ImageHeight
    p5.Image/pixels:
      - Image/CreateImage0
      - Image/P5ImagePixels
    p5.Image/loadPixels():
      - Image/P5ImageLoadPixels
    p5.Image/updatePixels():
      - Image/P5ImageLoadPixels
    p5.Image/get(), p5.Image/getPixel(), p5.Image/getRegion():
      - Image/P5ImageGet
    p5.Image/set(), p5.Image/setPixel(), p5.Image/setImage():
      - Image/CreateImage1
    p5.Image/resize():
      - Image/P5ImageResize
    p5.Image/copy(), p5.Image/copyFrom():
      - Image/P5ImageCopy
    p5.Image/mask():
      - Image/P5ImageMask
    p5.Image/filter():
      - Image/P5ImageFilter
    p5.Image/blend(), p5.Image/blendFrom():
      - Image/P5ImageBlend0
      - Image/P5ImageBlend1
      - Image/P5ImageBlend2
    p5.Image/reset():
      - Image/P5ImageReset
    p5.Image/getCurrentFrame():
      - Image/P5ImageGetCurrentFrame
    p5.Image/setFrame():
      - Image/P5ImageSetFrame
    p5.Image/numFrames():
      - Image/P5ImageSetFrame
    p5.Image/play():
      - Image/P5ImagePlay
    p5.Image/pause():
      - Image/P5ImagePlay
    p5.Image/delay(), p5.Image/delayAtIndex():
      - Image/P5ImageDelay
    loadImage(), loadImageWithCallbacks():
      - Image/LoadImage0
      - Image/LoadImage1
    image(), imageWithSize(), imageWithOptions():
      - Image/Image0
      - Image/Image1
      - Image/LoadImage1
      - Image/Image2
      - Image/Image3
      - Image/Image4
    tint():
      - Image/Tint0
      - Image/Tint1
      - Image/Tint2
    noTint():
      - Image/NoTint
    imageMode():
      - Image/ImageMode0
      - Image/ImageMode1
      - Image/ImageMode2
    pixels:
      - Image/Pixels
    blend(), blendFrom():
      - Image/Blend0
      - Image/Blend1
      - Image/Blend2
    copy(), copyFrom():
      - Image/Copy
    filter():
      - Image/Filter0
      - Image/Filter1
      - Image/Filter2
      - Image/Filter3
      - Image/Filter4
      - Image/Filter5
      - Image/Filter6
      - Image/Filter7
    get(), getImage(), getPixel(), getRegion():
      - Image/Get0
      - Image/Get1
    loadPixels():
      - Image/LoadPixels
    updatePixels(), updatePixelRegion():
      - Image/LoadPixels
    set(), setPixel(), setImage():
      - Image/Set0
      - Image/Set1
      - Image/Set2
  Math:
    abs():
      - Math/Abs
    ceil():
      - Math/Ceil
    constrain():
      - Math/Constrain
    dist(), dist3D():
      - Math/Dist
    exp():
      - Math/Exp
    floor():
      - Math/Floor
    lerp():
      - Math/Lerp
    log():
      - Math/Log
    mag():
      - Math/Mag
