examples:
  Structure:
    Structure/Coordinates: Coordinates
    Structure/WidthAndHeight: Width and Height
    Structure/SetupAndDraw: Setup and Draw
    Structure/NoLoop: No Loop
    Structure/Loop: Loop
    Structure/Redraw: Redraw
    Structure/Functions: Functions
    Structure/Recursion: Recursion
    Structure/CreateGraphics: Create Graphics

  Form:
    Form/PointsAndLines: Points and Lines
    Form/ShapePrimitives: Shape Primitives
    Form/PieChart: Pie Chart

reference:
  Environment:
    describe(), describeWithDisplay():
      - Environment/Describe0
      - Environment/Describe1
    describeElement(), describeElementWithDisplay():
      - Environment/DescribeElement
    textOutput(), textOutputWithDisplay():
      - Environment/TextOutput0
      - Environment/TextOutput1
    gridOutput(), gridOutputWithDisplay():
      - Environment/GridOutput0
      - Environment/GridOutput1
    print():
      - Environment/Print
    frameCount:
        - Environment/FrameCount
    deltaTime:
        - Environment/DeltaTime
  Shape:
    circle():
      - Shape/Circle
