examples:
  Structure:
    Structure/Coordinates: Coordinates
    Structure/WidthAndHeight: Width and Height
    Structure/SetupAndDraw: Setup and Draw
    Structure/NoLoop: No Loop
    Structure/Loop: Loop
    Structure/Redraw: Redraw
    Structure/Functions: Functions
    Structure/Recursion: Recursion
    Structure/CreateGraphics: Create Graphics

  Form:
    Form/PointsAndLines: Points and Lines
    Form/ShapePrimitives: Shape Primitives
    Form/PieChart: Pie Chart

reference:
  Environment:
    describe(), describeWithDisplay():
      - Environment/Describe0
      - Environment/Describe1
    describeElement(), describeElementWithDisplay():
      - Environment/DescribeElement
    textOutput(), textOutputWithDisplay():
      - Environment/TextOutput0
      - Environment/TextOutput1
    gridOutput(), gridOutputWithDisplay():
      - Environment/GridOutput0
      - Environment/GridOutput1
    print():
      - Environment/Print
    frameCount:
      - Environment/FrameCount
    deltaTime:
      - Environment/DeltaTime
    focused:
      - Environment/Focused
    cursor(), cursorX(), cursorXY():
      - Environment/Cursor
    frameRate(), getFrameRate(), setFrameRate():
      - Environment/FrameRate
    getTargetFrameRate():
      - Environment/GetTargetFrameRate
    noCursor():
      - Environment/NoCursor
    displayWidth:
      - Environment/DisplayWidth
    displayHeight:
      - Environment/DisplayWidth
    windowWidth:
      - Environment/WindowWidth
    windowHeight:
      - Environment/WindowWidth
    windowResized():
      - Environment/WindowResized
    width:
      - Environment/DisplayDensity
    height:
      - Environment/DisplayDensity
    fullscreen(), getFullscreen(), setFullscreen():
      - Environment/Fullscreen
    pixelDensity(), getPixelDensity(), setPixelDensity():
      - Environment/PixelDensity0
      - Environment/PixelDensity1
    displayDensity(), getDisplayDensity():
      - Environment/DisplayDensity
    getURL():
      - Environment/GetUrl
    getURLPath():
      - Environment/GetUrlPath
    getURLParams():
      - Environment/GetUrlParams
  Color:
    alpha():
      - Color/Alpha
    blue():
      - Color/Blue
    brightness():
      - Color/Brightness0
      - Color/Brightness1
    color():
      - Color/Color0
      - Color/Color1
      - Color/Color2
      - Color/Color3
      - Color/Color4
      - Color/Color5
      - Color/Color6
      - Color/Color7
    green():
      - Color/Green
    hue():
      - Color/Hue
    lerpColor():
      - Color/LerpColor
    lightness():
      - Color/Lightness
    red():
      - Color/Red
    saturation():
      - Color/Saturation
    background():
      - Color/Background0
      - Color/Background1
      - Color/Background2
      - Color/Background3
      - Color/Background4
      - Color/Background5
      - Color/Background6
      - Color/Background7
      - Color/Background8
      - Color/Background9
      - Color/Background10
    clear(), clearWebgl():
      - Color/Clear
    colorMode(), colorModeMaxAll(), colorModeMax(), colorModeMaxAlpha():
      - Color/ColorMode0
      - Color/ColorMode1
      - Color/ColorMode2
      - Color/ColorMode3
    fill():
      - Color/Fill0
      - Color/Fill1
      - Color/Fill2
      - Color/Fill3
      - Color/Fill4
      - Color/Fill5
      - Color/Fill6
      - Color/Fill7
      - Color/Fill8
      - Color/Fill9
      - Color/Fill10
    noFill():
      - Color/NoFill0
      - Color/NoFill1
    noStroke():
      - Color/NoStroke0
      - Color/NoStroke1
    stroke():
      - Color/Stroke0
      - Color/Stroke1
      - Color/Stroke2
      - Color/Stroke3
      - Color/Stroke4
      - Color/Stroke5
      - Color/Stroke6
      - Color/Stroke7
      - Color/Stroke8
      - Color/Stroke9
      - Color/Stroke10
    erase():
      - Color/Erase0
      - Color/Erase1
      - Color/Erase2
    noErase():
      - Color/NoErase
    p5.Color/toString(), p5.Color/toStringf():
      - Color/P5ColorToString0
      - Color/P5ColorToString1
    p5.Color/setRed():
      - Color/P5ColorSetRed
    p5.Color/setGreen():
      - Color/P5ColorSetGreen
    p5.Color/setBlue():
      - Color/P5ColorSetBlue
    p5.Color/setAlpha():
      - Color/P5ColorSetAlpha
  Shape:
    arc(), arcWithMode(), archWithDetail():
      - Shape/Arc0
      - Shape/Arc1
      - Shape/Arc2
      - Shape/Arc3
      - Shape/Arc4
    ellipse():
      - Shape/Ellipse
    circle():
      - Shape/Circle
    line(), line2D(), line3D():
      - Shape/Line0
      - Shape/Line1
    point(), point2D(), point3D(), pointFromVector():
      - Shape/Point0
      - Shape/Point1
      - Shape/Point2
    quad(), quad3D(), quadWithDetail(), quad3DWithDetail():
      - Shape/Quad
    rect(), roundedRect(), rectWithDetail():
      - Shape/Rect0
      - Shape/Rect1
      - Shape/Rect2
    square(), roundedSquare():
      - Shape/Square0
      - Shape/Square1
      - Shape/Square2
    triangle():
      - Shape/Triangle
    ellipseMode():
      - Shape/EllipseMode0
      - Shape/EllipseMode1
    noSmooth():
      - Shape/NoSmooth
    rectMode():
      - Shape/RectMode0
      - Shape/RectMode1
    smooth():
      - Shape/NoSmooth
    strokeCap():
      - Shape/StrokeCap
    strokeJoin():
      - Shape/StrokeJoin0
      - Shape/StrokeJoin1
      - Shape/StrokeJoin2
    strokeWeight():
      - Shape/StrokeWeight0
      - Shape/StrokeWeight1
    bezier(), bezier3D():
      - Shape/Bezier0
      - Shape/Bezier1
    bezierDetail():
      - Shape/BezierDetail
    bezierPoint():
      - Shape/BezierPoint
    bezierTangent():
      - Shape/BezierTangent0
      - Shape/BezierTangent1
    curve(), curve3D():
      - Shape/Curve0
      - Shape/Curve1
      - Shape/Curve2
    curveDetail():
      - Shape/CurveDetail
    curveTightness():
      - Shape/CurveTightness
    curvePoint():
      - Shape/CurvePoint
    curveTangent():
      - Shape/CurveTangent
    beginContour():
      - Shape/BeginContour
    endContour():
      - Shape/BeginContour
    bezierVertex(), bezierVertex3D():
      - Shape/BezierVertex0
      - Shape/BezierVertex1
      - Shape/BezierVertex2
    curveVertex(), curveVertex3D():
      - Shape/CurveVertex
    beginShape(), beginShapeWithMode():
      - Shape/BeginShape0
      - Shape/BeginShape1
      - Shape/BeginShape2
      - Shape/BeginShape3
      - Shape/BeginShape4
      - Shape/BeginShape5
      - Shape/BeginShape6
      - Shape/BeginShape7
      - Shape/BeginShape8
      - Shape/BeginShape9
      - Shape/BeginShape10
    quadraticVertex(), quadraticVertex3D():
      - Shape/QuadraticVertex0
      - Shape/QuadraticVertex1
    vertex(), vertex3D():
      - Shape/Vertex0
      - Shape/Vertex1
      - Shape/Vertex2
      - Shape/Vertex3
      - Shape/Vertex4
    normal():
      - Shape/Normal
    plane():
      - Shape/Plane
    box(), cube(), boxWithDetail():
      - Shape/Box
    sphere(), sphereWithDetail():
      - Shape/Sphere0
      - Shape/Sphere1
      - Shape/Sphere2
    cylinder(), cylinderWithDefaults(), cylinderWithDetail(), cylinderWithDetailAndCap():
      - Shape/Cylinder0
      - Shape/Cylinder1
      - Shape/Cylinder2
    cone(), coneWithDefaults(), coneWithDetail(), coneWithDetailAndCap():
      - Shape/Cone0
      - Shape/Cone1
      - Shape/Cone2
    ellipsoid(), ellipsoidWithDefaults(), ellipsoidWithDetail():
      - Shape/Ellipsoid0
      - Shape/Ellipsoid1
      - Shape/Ellipsoid2
